// FCM 등록 위한 Firebase app 초기화, getMessaging() 설정파일

// 필요한 환경변수 목록
// VITE_FIREBASE_API_KEY=
// VITE_FIREBASE_AUTH_DOMAIN=
// VITE_FIREBASE_PROJECT_ID=
// VITE_FIREBASE_MESSAGING_SENDER_ID=
// VITE_FIREBASE_APP_ID=
// VITE_FIREBASE_VAPID_KEY=